---
- name: centos | install needed packages
  yum:
      update_cache: true
      name: '{{ v_centos_needed_pkg }}'
      state: latest

- name: RedHat - Install {{ beat }} from url
  become: yes
  yum:
    name: >-
      {% if custom_package_url is defined %}{{ custom_package_url }}{%
        else %}{{ beats_package_url }}/{{ beat }}-{{ beats_version }}-{{ ansible_architecture }}.rpm{% endif %}
    state: present
    validate_certs: no
  register: beat_install
  until: beat_install is succeeded
  # notify: restart the service
