---
- name: 'Checkos | Check linux os compatibility'
  ansible.builtin.fail:
    msg: 'Linux distribution {{ ansible_distribution }} not supported'
  when: ansible_system == 'Linux' and
        ((ansible_distribution != 'Debian' and ansible_distribution_major_version|int < 9) and
        (ansible_distribution != 'CentOS' and ansible_distribution_major_version|int < 6))

- name: 'Checkos | Check windows os compatibility'
  ansible.builtin.fail:
    msg: 'Windows version {{ ansible_distribution }} not supported'
  when: ansible_system == 'Win32NT' and ansible_distribution_major_version|int < 6
