---
- name: checkos | check linux os compatibility
  fail:
      msg: 'Linux distribution {{ ansible_distribution }} not supported'
  when: ansible_system == 'Linux' and (ansible_distribution != 'Debian' and ansible_distribution != 'CentOS')

- name: checkos | check windows os compatibility
  fail:
    msg: 'Windows version {{ ansible_distribution }} not supported'
  when: ansible_system == 'Win32NT' and ansible_distribution_major_version < 6