---

- name: Define current api path
  ansible.builtin.set_fact:
    apipath: "{{ api | community.general.json_query(query) }}"
  vars:
    query: "[?paths.version=='{{ rgmapi_version }}'].paths"


- name: Create_rgm_server | get rgm token
  ansible.builtin.uri:
    url: 'https://{{ rgm_server }}/{{ apipath[0].gettokenpath }}?username={{ rgm_username }}&password={{ rgm_password }}'
    remote_src: true
    method: GET
    status_code: 200
    validate_certs: false
  register: rgm_token

- name: Create_rgm_server | check rgm host
  ansible.builtin.uri:
    url: 'https://{{ rgm_server }}/rgmapi/getHost'
    method: POST
    body:
      token: "{{ rgm_token.json.RGMAPI_TOKEN }}"
      hostName: "{{ ansible_nodename }}"
      hostIp: "{{ ansible_default_ipv4['address'] }}"
      templateHostName: "{{ d_rgm_template }}"
    body_format: json
    validate_certs: false
  register: get_rgm_server_task

- name: Create_rgm_server | create rgm host
  ansible.builtin.uri:
    url: 'https://{{ rgm_server }}/{{ apipath[0].createhostpath }}'
    method: POST
    body:
      token: "{{ rgm_token.json.RGMAPI_TOKEN }}"
      hostName: "{{ ansible_nodename }}"
      hostIp: "{{ ansible_default_ipv4['address'] }}"
      templateHostName: "{{ d_rgm_template }}"
      exportConfiguration: true
    body_format: json
    validate_certs: false
  when: get_rgm_server_task.json.result is not mapping

- name: Create_rgm_server | export configuration
  ansible.builtin.uri:
    url: 'https://{{ rgm_server }}/{{ apipath[0].exportconfpath }}'
    method: POST
    body:
      token: "{{ rgm_token.json.RGMAPI_TOKEN }}"
      jobName: "{{ d_rgm_exportjob_name }}"
    body_format: json
    status_code: 200
    validate_certs: false
  when: get_rgm_server_task.json.result is not mapping
