---

- name: define current api path
  set_fact:
    apipath: "{{ api | community.general.json_query(query) }}"
  vars:
    query: "[?paths.version=='{{ rgmapi_version }}'].paths"


- name: create_rgm_host | get rgm token
  uri:
    url: 'https://{{ rgm_ip }}/{{ apipath[0].gettokenpath }}?username={{ rgm_adm_username }}&password={{ rgm_adm_password }}'
    remote_src: true
    method: GET
    status_code: 200
    validate_certs: false
  register: rgm_token

- name: create_rgm_host | create rgm host
  uri:
    url: 'https://{{ rgm_ip }}/{{ apipath[0].createhostpath }}'
    method: POST
    body:
      token: "{{ rgm_token.json.RGMAPI_TOKEN }}"
      hostName: "{{ ansible_nodename }}"
      hostIp: "{{ ansible_default_ipv4['address'] }}"
      templateHostName: "{{ d_rgm_template }}"
      exportConfiguration: true
    body_format: json
    validate_certs: false

- name: create_rgm_host | export configuration
  uri:
    url: 'https://{{ rgm_ip }}/{{ apipath[0].exportconfpath }}'
    method: POST
    body:
      token: "{{ rgm_token.json.RGMAPI_TOKEN }}"
      jobName: "{{ d_rgm_exportjob_name }}"
    body_format: json
    status_code: 200
    validate_certs: false
