---

- name: 'Create_rgm_host | define current api path'
  vars:
    query: "[?paths.version=='{{ rgmapi_version }}'].paths"
  ansible.builtin.set_fact:
    apipath: "{{ api | community.general.json_query(query) }}"

- name: 'Create_rgm_host | get rgm token'
  register: rgm_token
  ansible.builtin.uri:
    url: 'https://{{ rgm_server }}/{{ apipath[0].gettokenpath }}?username={{ rgm_username }}&password={{ rgm_password }}'
    remote_src: true
    method: POST
    status_code:
      - 201
    validate_certs: false

- name: 'Create_rgm_host | Check rgm host'
  register: get_rgm_server_task
  ansible.builtin.uri:
    url: 'https://{{ rgm_server }}/{{ apipath[0].createhostpath }}'
    method: GET
    body:
      hostName: "{{ ansible_nodename }}"
      hostIp: "{{ ansible_default_ipv4['address'] }}"
      templateHostName: "{{ d_rgm_template }}"
    body_format: json
    validate_certs: false
    headers:
      Authorization: 'Bearer {{ rgm_token.json.token }}'

- name: 'Create_rgm_host | Create rgm host'
  when: get_rgm_server_task.json.result is not mapping
  ansible.builtin.uri:
    url: 'https://{{ rgm_server }}/{{ apipath[0].createhostpath }}'
    method: POST
    body:
      hostName: "{{ ansible_nodename }}"
      hostIp: "{{ ansible_default_ipv4['address'] }}"
      templateHostName: "{{ d_rgm_template }}"
      exportConfiguration: true
    body_format: json
    validate_certs: false
    status_code:
      - 201
    headers:
      Authorization: 'Bearer {{ rgm_token.json.token }}'

- name: 'Create_rgm_host | Export configuration'
  when: get_rgm_server_task.json.result is not mapping
  ansible.builtin.uri:
    url: 'https://{{ rgm_server }}/{{ apipath[0].exportconfpath }}'
    method: POST
    body:
      jobName: "{{ d_rgm_exportjob_name }}"
    body_format: json
    status_code:
      - 201
    validate_certs: false
    headers:
      Authorization: 'Bearer {{ rgm_token.json.token }}'
