---
- name: Debian - Check if {{ beat }}  package is installed
  ansible.builtin.package_facts:
    manager: apt

- name: Debian - unhold {{ beat }} version for install
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ beat }}"
    selection: "install"
  when: beat in ansible_facts.packages
  changed_when: false

- name: Set os_arch
  ansible.builtin.set_fact:
    os_arch: "amd64"
    # os_arch: >-
    #   {{ (ansible_architecture == 'x86_64') | ternary('amd64', 'i386') }}

- name: Debian - Download {{ beat }} from url
  ansible.builtin.get_url:
    url: >-
      {% if custom_package_url is defined %}{{ custom_package_url }}{%
        else %}{{ beats_package_url }}/{{ beat }}-{{ beats_version }}-{{ os_arch }}.deb{% endif %}
    dest: "/tmp/{{ beat }}_{{ beats_version }}_{{ os_arch }}.deb"
    validate_certs: false

- name: Debian - Ensure {{ beat }} is installed from downloaded package
  become: true
  ansible.builtin.apt:
    deb: "/tmp/{{ beat }}_{{ beats_version }}_{{ os_arch }}.deb"
  # when: not use_repository | bool
  # notify: restart the service
