---
- name: delete | get service status
  ansible.windows.win_service:
    name: 'metricbeat'
  when: ansible_system == 'Win32NT'
  register: service_info

- name: delete | stop metricbeat service
  ansible.windows.win_service:
    name: 'metricbeat'
    state: stopped
  when: service_info['exists'] and service_info['state'] == "running" and ansible_system == 'Win32NT'

- name: delete | remove metricbeat service
  ansible.windows.win_shell: (Get-WmiObject Win32_Service -filter "name='metricbeat'").Delete()
  when: service_info['exists'] and ansible_system == 'Win32NT'
