---
- name: 'Delete | get service status'
  when: ansible_system == 'Win32NT'
  register: service_info
  ansible.windows.win_service:
    name: 'metricbeat'

- name: 'Delete | stop metricbeat service'
  when: service_info['exists'] and service_info['state'] == "running" and ansible_system == 'Win32NT'
  ansible.windows.win_service:
    name: 'metricbeat'
    state: stopped

- name: 'Delete | remove metricbeat service'
  when: service_info['exists'] and ansible_system == 'Win32NT'
  ansible.windows.win_shell: (Get-WmiObject Win32_Service -filter "name='metricbeat'").Delete()
