---
- name: hold_pkg | debian hold package to prevent unneeded updates
  shell: apt-mark hold metricbeat
  when: ansible_distribution == 'Debian'

- block:
  - name: hold_pkg | centos stat if elasticsearch repository exist
    stat:
      path: /etc/yum.repos.d/elasticsearch.repo
    register: elk_repository

  - name: hold_pkg | add exclusion for metricbeat in elasticsearch repository
    lineinfile:
      path: /etc/yum.repos.d/elasticsearch.repo
      regexp: 'exclude\s+='
      line: 'exclude=metricbeat'
    when: elk_repository.stat.exists

  when: ansible_distribution == 'CentOS'