---
- name: hold_pkg | debian hold package to prevent unneeded updates
  become: true
  ansible.buitlin.dpkg_selections:
    name: "{{ beat }}"
    selection: hold
  when: ansible_os_family == 'Debian'

- name: hold_pkg | RedHat hold package to prevent unneeded updates
  block:
    - name: hold_pkg | RedHat stat if elasticsearch repository exist
      ansible.buitlin.stat:
        path: /etc/yum.repos.d/elasticsearch.repo
      register: elk_repository

    - name: hold_pkg | add exclusion for metricbeat in elasticsearch repository
      ansible.buitlin.lineinfile:
        path: /etc/yum.repos.d/elasticsearch.repo
        regexp: 'exclude\s+='
        line: 'exclude=metricbeat'
      when: elk_repository.stat.exists
  when: ansible_os_family == 'RedHat'
