---
- name: 'Hold_pkg | Debian hold package to prevent unneeded updates'
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ beat }}"
    selection: hold
  when: ansible_os_family == 'Debian'

- name: 'Hold_pkg | RedHat hold package to prevent unneeded updates'
  when: ansible_os_family == 'RedHat'
  block:
    - name: 'Hold_pkg | RedHat stat if elasticsearch repository exist'
      register: elk_repository
      ansible.builtin.stat:
        path: /etc/yum.repos.d/elasticsearch.repo

    - name: 'Hold_pkg | Add exclusion for metricbeat in elasticsearch repository'
      when: elk_repository.stat.exists
      ansible.builtin.lineinfile:
        path: /etc/yum.repos.d/elasticsearch.repo
        regexp: 'exclude\s+='
        line: 'exclude=metricbeat'
