---
- name: Linux | test is metricbeat already deployed
  ansible.builtin.stat:
    path: /etc/metricbeat
  register: metricbeat_conf_dir

- name: Linux | import debian specific tasks
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Linux | import centos specific tasks
  ansible.builtin.import_tasks: centos.yml
  when: ansible_os_family == 'RedHat'

- name: Linux | deploy rgm system metrics configurations
  become: true
  ansible.builtin.get_url:
    url: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: "0644"
    validate_certs: false
  loop:
    - {src: '{{ metricbeat_linux_conf_path }}/linux_metricbeat.yml', dest: '/etc/metricbeat/metricbeat.yml'}
    - {src: '{{ metricbeat_linux_conf_path }}/modules/linux_rgm-system-core.yml', dest: '/etc/metricbeat/modules.d/rgm-system-core.yml'}
    - {src: '{{ metricbeat_linux_conf_path }}/modules/linux_rgm-system-fs.yml', dest: '/etc/metricbeat/modules.d/rgm-system-fs.yml'}
    - {src: '{{ metricbeat_linux_conf_path }}/modules/linux_rgm-system-uptime.yml', dest: '/etc/metricbeat/modules.d/rgm-system-uptime.yml'}
  tags:
    - configure

- name: Linux | set current host IP in linux_metricbeat.yml
  become: true
  ansible.builtin.lineinfile:
    path: /etc/metricbeat/metricbeat.yml
    regexp: '^  host.ip: %%IP%%$'
    line: "  host.ip: {{ ansible_default_ipv4.address }}"

- name: Linux | Change linux_metricbeat.yml ownership, group and permissions
  become: true
  ansible.builtin.file:
    path: /etc/metricbeat/metricbeat.yml
    owner: root
    group: root
    mode: '0640'


- name: Linux | test is metricbeat default system module is active
  ansible.builtin.stat:
    path: /etc/metricbeat/modules.d/system.yml
  register: metricbeat_system_mod
  tags:
    - configure

- name: Linux | copy original system module configuration
  become: true
  ansible.builtin.copy:
    src: '/etc/metricbeat/modules.d/system.yml'
    dest: '/etc/metricbeat/modules.d/system.yml.disabled'
    remote_src: true
    mode: "0644"
  when: metricbeat_system_mod.stat.exists
  tags:
    - configure

- name: Linux | delete active default system module
  become: true
  ansible.builtin.file:
    path: '/etc/metricbeat/modules.d/system.yml'
    state: absent
  when: metricbeat_system_mod.stat.exists
  tags:
    - configure

- name: Linux | import hold_pkg.yml
  ansible.builtin.import_tasks: hold_pkg.yml

- name: Linux | import create rgm host
  ansible.builtin.import_tasks: create_rgm_host.yml
  when: not metricbeat_conf_dir.stat.exists or force_rgm_registration is defined

- name: Linux | Pause before start service
  ansible.builtin.pause:
    seconds: 5

- name: Linux | restart metricbeat service
  become: true
  ansible.builtin.service:
    name: metricbeat
    state: restarted
