---
- name: 'Linux | Test is metricbeat already deployed'
  register: metricbeat_conf_dir
  ansible.builtin.stat:
    path: /etc/metricbeat

- name: 'Linux | Import debian specific tasks'
  when: ansible_os_family == 'Debian'
  ansible.builtin.import_tasks: debian.yml

- name: 'Linux | Import centos specific tasks'
  when: ansible_os_family == 'RedHat'
  ansible.builtin.import_tasks: centos.yml

- name: 'Linux | Deploy rgm system metrics configurations'
  become: true
  loop:
    - {src: '{{ metricbeat_linux_conf_path }}/linux_metricbeat.yml', dest: '/etc/metricbeat/metricbeat.yml'}
    - {src: '{{ metricbeat_linux_conf_path }}/modules/linux_rgm-system-core.yml', dest: '/etc/metricbeat/modules.d/rgm-system-core.yml'}
    - {src: '{{ metricbeat_linux_conf_path }}/modules/linux_rgm-system-fs.yml', dest: '/etc/metricbeat/modules.d/rgm-system-fs.yml'}
    - {src: '{{ metricbeat_linux_conf_path }}/modules/linux_rgm-system-uptime.yml', dest: '/etc/metricbeat/modules.d/rgm-system-uptime.yml'}
  tags:
    - configure
  ansible.builtin.get_url:
    url: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    validate_certs: false

- name: 'Linux | Set current host IP in linux_metricbeat.yml'
  become: true
  ansible.builtin.lineinfile:
    path: /etc/metricbeat/metricbeat.yml
    regexp: '^  host.ip: %%IP%%$'
    line: "  host.ip: {{ ansible_default_ipv4.address }}"

- name: 'Linux | Change linux_metricbeat.yml ownership, group and permissions'
  become: true
  ansible.builtin.file:
    path: /etc/metricbeat/metricbeat.yml
    owner: 'root'
    group: 'root'
    mode: '0640'


- name: 'Linux | Test is metricbeat default system module is active'
  register: metricbeat_system_mod
  tags:
    - configure
  ansible.builtin.stat:
    path: /etc/metricbeat/modules.d/system.yml

- name: 'Linux | Copy original system module configuration'
  become: true
  when: metricbeat_system_mod.stat.exists
  tags:
    - configure
  ansible.builtin.copy:
    src: '/etc/metricbeat/modules.d/system.yml'
    dest: '/etc/metricbeat/modules.d/system.yml.disabled'
    remote_src: true
    mode: '0644'


- name: 'Linux | Delete active default system module'
  become: true
  when: metricbeat_system_mod.stat.exists
  tags:
    - configure
  ansible.builtin.file:
    path: '/etc/metricbeat/modules.d/system.yml'
    state: absent

- name: 'Linux | Import hold_pkg.yml'
  ansible.builtin.import_tasks: hold_pkg.yml

- name: 'Linux | Import create rgm host'
  when: not metricbeat_conf_dir.stat.exists or force_rgm_registration is defined
  ansible.builtin.import_tasks: create_rgm_host.yml

- name: 'Linux | Pause before start service'
  ansible.builtin.pause:
    seconds: 5

- name: 'Linux | Restart metricbeat service'
  become: true
  ansible.builtin.service:
    name: metricbeat
    state: restarted
