---
- name: linux | import debian specific tasks
  import_tasks: debian.yml
  when: ansible_distribution == 'Debian'

- name: linux | import centos specific tasks
  import_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- name: linux | test is metricbeat already deployed
  stat:
    path: /etc/metricbeat
  register: metricbeat_conf_dir

- name: linux | import metricbeat deployement and rgm config
  import_tasks: deploy.yml
  when: metricbeat_conf_dir.stat.exists != True

- name: linux | deploy rgm system metrics configurations
  template:
    dest: '{{ item.dest }}'
    src: '{{ item.src }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'metricbeat/module-system-core.yml.j2', dest: '/etc/metricbeat/modules.d/rgm-system-core.yml' }
    - { src: 'metricbeat/module-system-fs.yml.j2', dest: '/etc/metricbeat/modules.d/rgm-system-fs.yml' }
    - { src: 'metricbeat/module-system-uptime.yml.j2', dest: '/etc/metricbeat/modules.d/rgm-system-uptime.yml' } 
  notify: restart metricbeat service
  tags:
    - configure

- name: linux | test is metricbeat default system module is active
  stat:
    path: /etc/metricbeat/modules/system.yml
  register: metricbeat_system_mod
  tags:
    - configure

- name: linux | copy original system module configuration
  copy:
    src: '/etc/metricbeat/modules.d/system.yml'
    dest: '/etc/metricbeat/modules.d/system.yml.disabled'
    remote_src: yes
  notify: restart metricbeat service
  when: metricbeat_system_mod.stat.exists == True
  tags:
    - configure

- name: linux | delete active default system module
  file:
    path: '/etc/metricbeat/modules.d/system.yml'
    state: absent
  notify: restart metricbeat service
  when: metricbeat_system_mod.stat.exists == True
  tags:
    - configure  

- name: linux | import create rgm host
  import_tasks: create_rgm_host.yml
  when: metricbeat_conf_dir.stat.exists != True