---
- name: 'Linux | Test is metricbeat already deployed'
  register: metricbeat_conf_dir
  ansible.builtin.stat:
    path: /etc/metricbeat

- name: 'Linux | Import debian specific tasks'
  when: ansible_os_family == 'Debian'
  ansible.builtin.import_tasks: debian.yml

- name: 'Linux | Import centos specific tasks'
  when: ansible_os_family == 'RedHat'
  ansible.builtin.import_tasks: centos.yml

- name: 'Linux | Deploy rgm system metrics configurations'
  become: true
  loop:
    - {src: '{{ metricbeat_linux_conf_path }}/linux_metricbeat.yml', dest: '/etc/metricbeat/metricbeat.yml'}
    - {src: '{{ metricbeat_linux_conf_path }}/modules/linux_rgm-system-core.yml', dest: '/etc/metricbeat/modules.d/rgm-system-core.yml'}
    - {src: '{{ metricbeat_linux_conf_path }}/modules/linux_rgm-system-fs.yml', dest: '/etc/metricbeat/modules.d/rgm-system-fs.yml'}
    - {src: '{{ metricbeat_linux_conf_path }}/modules/linux_rgm-system-uptime.yml', dest: '/etc/metricbeat/modules.d/rgm-system-uptime.yml'}
  tags:
    - configure
  ansible.builtin.get_url:
    url: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    validate_certs: false

- name: 'Linux | Update configuration'
  become: true
  tags:
    - configure
  loop:
    - { rex: '^  host.ip: \{\{ client_ip_addr \}\}', line: "  host.ip: {{ ansible_default_ipv4.address }}" }
    - { rex: '^  hosts: \[".*\:443"\]', line: '  hosts: ["{{ rgm_server }}:443"]' }
  ansible.builtin.lineinfile:
    path: /etc/metricbeat/metricbeat.yml
    regexp: '{{ item.rex }}'
    line: '{{ item.line }}'

- name: 'Linux | Fix configuration for RHEL 9 systems'
  become: true
  tags:
    - configure
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int >= 9
  ansible.builtin.blockinfile:
    path: '/etc/metricbeat/metricbeat.yml'
    insertafter: '#logging.selectors: ["*"]'
    marker: '# {mark} ANSIBLE CONFIGURED BLOCK'
    block: |
      seccomp:
        default_action: errno
        syscalls:
        - action: allow
          names:
            - accept
            - accept4
            - access
            - arch_prctl
            - bind
            - brk
            - chmod
            - chown
            - clock_gettime
            - clone
            - clone3
            - close
            - connect
            - dup
            - dup2
            - epoll_create
            - epoll_create1
            - epoll_ctl
            - epoll_pwait
            - epoll_wait
            - exit
            - exit_group
            - fchdir
            - fchmod
            - fchmodat
            - fchown
            - fchownat
            - fcntl
            - fdatasync
            - flock
            - fstat
            - fstatfs
            - fsync
            - ftruncate
            - futex
            - getcwd
            - getdents
            - getdents64
            - geteuid
            - getgid
            - getpeername
            - getpid
            - getppid
            - getrandom
            - getrlimit
            - getrusage
            - getsockname
            - getsockopt
            - gettid
            - gettimeofday
            - getuid
            - inotify_add_watch
            - inotify_init1
            - inotify_rm_watch
            - ioctl
            - kill
            - listen
            - lseek
            - lstat
            - madvise
            - mincore
            - mkdirat
            - mmap
            - mprotect
            - munmap
            - nanosleep
            - newfstatat
            - open
            - openat
            - pipe
            - pipe2
            - poll
            - ppoll
            - pread64
            - pselect6
            - pwrite64
            - read
            - readlink
            - readlinkat
            - recvfrom
            - recvmmsg
            - recvmsg
            - rename
            - renameat
            - rt_sigaction
            - rt_sigprocmask
            - rt_sigreturn
            - sched_getaffinity
            - sched_yield
            - sendfile
            - sendmmsg
            - sendmsg
            - sendto
            - set_robust_list
            - setitimer
            - setsockopt
            - shutdown
            - sigaltstack
            - socket
            - splice
            - stat
            - statfs
            - sysinfo
            - tgkill
            - time
            - tkill
            - uname
            - unlink
            - unlinkat
            - wait4
            - waitid
            - write
            - writev

- name: 'Linux | Change linux_metricbeat.yml ownership, group and permissions'
  become: true
  ansible.builtin.file:
    path: /etc/metricbeat/metricbeat.yml
    owner: 'root'
    group: 'root'
    mode: '0640'

- name: 'Linux | Test is metricbeat default system module is active'
  register: metricbeat_system_mod
  tags:
    - configure
  ansible.builtin.stat:
    path: /etc/metricbeat/modules.d/system.yml


- name: 'Linux | Copy original system module configuration'
  become: true
  when: metricbeat_system_mod.stat.exists
  tags:
    - configure
  ansible.builtin.copy:
    src: '/etc/metricbeat/modules.d/system.yml'
    dest: '/etc/metricbeat/modules.d/system.yml.disabled'
    remote_src: true
    mode: '0644'

- name: 'Linux | Delete active default system module'
  become: true
  when: metricbeat_system_mod.stat.exists
  tags:
    - configure
  ansible.builtin.file:
    path: '/etc/metricbeat/modules.d/system.yml'
    state: absent

- name: 'Linux | Import hold_pkg.yml'
  ansible.builtin.import_tasks: hold_pkg.yml

- name: 'Linux | Import create rgm host'
  when: not metricbeat_conf_dir.stat.exists or force_rgm_registration is defined
  ansible.builtin.import_tasks: create_rgm_host.yml

- name: 'Linux | Pause before start service'
  ansible.builtin.pause:
    seconds: 5

- name: 'Linux | Restart metricbeat service'
  become: true
  ansible.builtin.service:
    name: metricbeat
    state: restarted
