---
- name: check os compatibility
  fail:
      msg: 'Os {{ ansible_distribution }} not supported'
  when: ansible_distribution != 'Debian' and ansible_distribution != 'CentOS'

- name: import linux tasks
  import_tasks: linux.yml
  when: ansible_distribution == 'Debian' and ansible_distribution == 'CentOS'