---
- name: 'Import check os'
  ansible.builtin.import_tasks: checkos.yml

- name: 'Import linux tasks'
  when: ( ansible_os_family == 'Debian' or  ansible_os_family == 'RedHat') and  ansible_system == 'Linux' and remove_metricbeat_services == 'no'
  ansible.builtin.import_tasks: linux.yml

- name: 'Import windows tasks'
  when:
    - ansible_distribution_major_version|int > 5
    - ansible_system == 'Win32NT'
    - remove_metricbeat_services == 'no'
  ansible.builtin.import_tasks: windows.yml

- name: 'Import service removing tasks'
  when: remove_metricbeat_services == 'yes'
  ansible.builtin.import_tasks: delete.yml
