---
- name: 'Windows | get service status'
  register: service_info
  ansible.windows.win_service:
    name: 'metricbeat'

- name: 'Windows | notify handler to restart service'
  notify: win restart metricbeat service
  changed_when: true
  when: service_info['exists'] and service_info['state'] != "running"
  ansible.builtin.debug:
    msg: restart metricbeat service

- name: 'Windows | ensure temp directory exist'
  ansible.windows.win_file:
    path: 'C:\temp'
    state: directory

- name: 'Windows | download rgm oneliner script'
  when: not service_info['exists']
  ansible.windows.win_get_url:
    url: '{{ v_win_url_oneliner }}'
    dest: 'C:\temp\Add-RGMHost.ps1'
    validate_certs: false

- name: 'Windows | perform metricbeat installation and importation'
  when: not service_info['exists']
  notify: win restart metricbeat service
  ansible.windows.win_shell: |
    C:\temp\Add-RGMHost.ps1 -Username "{{ rgm_username }}" `
      -Password "{{ rgm_password }}" `
      -RGMServer "{{ rgm_server }}" `
      -RGMTemplate "{{ d_rgm_win_template }}" `
      -NoExportConfig:([System.Convert]::ToBoolean("{{ no_export_config | default(no, True) }}")) `
      -Verbose:([System.Convert]::ToBoolean("{{ script_verbose | default(no, True) }}"))

- name: 'Windows | remove downloaded rgm onliner script'
  ansible.windows.win_file:
    path: 'C:\temp\Add-RGMHost.ps1'
    state: absent
