---
- name: win restart metricbeat service
  ansible.windows.win_service:
    name: metricbeat
    state: restarted
    start_mode: auto

- name: restart metricbeat service
  ansible.builtin.service:
    name: metricbeat
    state: restarted
    sleep: 5
